---
exclude: 'node_modules/**'
linters:
  DisableLinterReason:
    enabled: true
  IdSelector:
    enabled: false
  LengthVariable:
    enabled: true
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  SelectorDepth:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  SpaceAfterVariableColon:
    enabled: true
  StringQuotes:
    style: double_quotes
  TrailingZero:
    enabled: true
