language: node_js
node_js:
  - "node"
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
sudo: false