---
extends: eslint-config-airbnb
parser: babel-eslint
plugins: [ babel, lodash, flow-vars ]
env: { es6: true, jasmine: true }
ecmaFeatures: { experimentalObjectRestSpread: true }
rules:
  # babel
  babel/generator-star-spacing: 2
  babel/new-cap: 2
  babel/object-curly-spacing: [ 2, never ]
  babel/object-shorthand: 2
  babel/arrow-parens: [ 2, as-needed ]
  babel/array-bracket-spacing: 2
  generator-star-spacing: 0
  new-cap: 0
  object-curly-spacing: 0
  object-shorthand: 0
  arrow-parens: 0
  array-bracket-spacing: 0

  # react
  react/jsx-closing-bracket-location: [ 2, tag-aligned ]
  react/jsx-curly-spacing: 2
  react/jsx-indent: [ 2, 2 ]
  react/jsx-no-duplicate-props: 2
  react/jsx-pascal-case: 2
  react/no-danger: 2
  react/no-direct-mutation-state: 2
  react/sort-comp: 0
  react/jsx-key: 2
  react/no-deprecated: 2
  react/jsx-equals-spacing: 2

  # lodash
  lodash/callback-binding: 2
  lodash/unwrap: 2
  lodash/no-double-unwrap: 2
  lodash/collection-return: 2
  lodash/prop-shorthand: 2
  lodash/matches-prop-shorthand: 2
  lodash/matches-shorthand: 2
  lodash/preferred-alias: 2
  lodash/prefer-chain: 2
  lodash/no-single-chain: 2
  lodash/prefer-reject: 2
  lodash/prefer-filter: 2
  lodash/prefer-compact: 2
  lodash/prefer-map: 2
  lodash/prefer-wrapper-method: 2
  lodash/prefer-invoke-map: 2
  lodash/prefer-thru: 2
  lodash/no-commit: 2
  lodash/chain-style: 2
  lodash/prefer-flat-map: 2
  lodash/prefer-lodash-chain: 2
  lodash/prefer-lodash-method: 2
  lodash/prefer-lodash-typecheck: 2
  lodash/prefer-get: 2
  lodash/prefer-matches: 2
  lodash/prefer-times: 2
  lodash/prefer-startswith: 2
  lodash/prefer-noop: 2
  lodash/prefer-constant: 2
  lodash/prefer-is-nil: 2
  lodash/prefer-over-quantifier: 2

  # flow
  flow-vars/define-flow-type: 2
  flow-vars/use-flow-type: 2

  # eslint
  no-inner-declarations: [ 2, both ]
  valid-jsdoc: [ 2, { prefer: { returns: return }, requireReturn: false } ]
  no-unexpected-multiline: 2
  accessor-pairs: 2
  block-spacing: 2
  complexity: [ 2, 11 ]
  curly: [ 2, all ]
  dot-location: [ 2, property ]
  padded-blocks: 0
  no-fallthrough: 0
  no-floating-decimal: 0
  no-div-regex: 2
  no-dupe-class-members: 2
  no-invalid-this: 2
  no-redeclare: [ 2, { builtinGlobals: true } ]
  no-return-assign: [ 2, always ]
  no-useless-call: 2
  no-void: 2
  no-warning-comments: [ 2, { terms: [ todo, fixme, xxx ], location: start } ]
  yoda: [ 2, always ]
  no-catch-shadow: 2
  no-label-var: 2
  no-undef-init: 2
  handle-callback-err: [ 2, "^err(or)?$" ]
  no-mixed-requires: [ 2, false ]
  no-new-require: 2
  no-param-reassign: 0
  no-path-concat: 2
  no-process-exit: 2
  no-sync: 2
  brace-style: [ 2, 1tbs ]
  camelcase: 2
  comma-dangle: [ 2, never ]
  consistent-this: [ 2, me ]
  indent: [ 2, 2, { SwitchCase: 1, VariableDeclarator: 2 } ]
  lines-around-comment: [ 2, { beforeBlockComment: true, beforeLineComment: true, allowBlockStart: true } ]
  linebreak-style: [ 2, unix ]
  new-parens: 2
  newline-after-var: 2
  no-array-constructor: 2
  no-inline-comments: 2
  no-lonely-if: 2
  no-multiple-empty-lines: [ 2, { max: 1 } ]
  one-var: 0
  operator-assignment: [ 2, always ]
  operator-linebreak: 2
  quote-props: [ 2, as-needed, { keywords: true } ]
  space-infix-ops: [ 2, { int32Hint: true } ]
  space-unary-ops: [ 2, { words: true, nonwords: false } ]
  arrow-parens: [ 2, as-needed ]
  constructor-super: 2
  no-class-assign: 2
  no-this-before-super: 2
  prefer-spread: 2
  require-yield: 2
  func-names: 0
  max-depth: [ 2, 4 ]
  max-len: [ 2, 120, 2 ]
  max-params: [ 2, 10 ]
  no-console: 0
  no-negated-condition: 2
  no-magic-numbers: [ 2, { enforceConst: true, detectObjects: true } ]
  no-empty-pattern: 2
  no-arrow-condition: 2
