---
extends: eslint-config-airbnb
plugins: [ babel, lodash ]
env: { es6: true, jasmine: true }
ecmaFeatures: { experimentalObjectRestSpread: true }
rules:
  # eslint-plugin-babel
  babel/generator-star-spacing: 2
  babel/new-cap: 2
  babel/object-curly-spacing: [ 2, never ]
  babel/object-shorthand: 2
  # generator-star-spacing: 2
  new-cap: 0
  # object-curly-spacing: [ 2, never ]
  # object-shorthand: 2

  # eslint-plugin-react
  react/jsx-closing-bracket-location: 2
  react/jsx-curly-spacing: 2
  react/jsx-indent-props: [ 2, 2 ]
  react/jsx-no-duplicate-props: 2
  react/no-danger: 2
  react/no-direct-mutation-state: 2
  react/sort-comp: 0

  # lodash
  lodash/import: 2

  # eslint
  no-inner-declarations: [ 2, both ]
  valid-jsdoc: [ 2, { prefer: { returns: return }, requireReturn: false } ]
  no-unexpected-multiline: 2
  accessor-pairs: 2
  block-spacing: 2
  complexity: [ 2, 11 ]
  curly: [ 2, all ]
  dot-location: [ 2, object ]
  padded-blocks: 0
  no-fallthrough: 0
  no-floating-decimal: 0
  no-div-regex: 2
  no-dupe-class-members: 2
  no-invalid-this: 2
  no-process-env: 2
  no-redeclare: [ 2, { builtinGlobals: true } ]
  no-return-assign: [ 2, always ]
  no-useless-call: 2
  no-void: 2
  no-warning-comments: [ 2, { terms: [ todo, fixme, xxx ], location: start } ]
  wrap-iife: 2
  yoda: [ 2, always ]
  no-catch-shadow: 2
  no-label-var: 2
  no-undef-init: 2
  no-use-before-define: [ 2, nofunc ]
  callback-return: 2
  handle-callback-err: [ 2, "^err(or)?$" ]
  no-mixed-requires: [ 2, false ]
  no-new-require: 2
  no-param-reassign: 0
  no-path-concat: 2
  no-process-exit: 2
  no-sync: 2
  array-bracket-spacing: [ 2, never ]
  brace-style: [ 2, 1tbs ]
  camelcase: 2
  comma-dangle: [ 2, never ]
  computed-property-spacing: [ 2, never ]
  consistent-this: [ 2, me ]
  indent: [ 2, 2, { SwitchCase: 1, VariableDeclarator: 2 } ]
  lines-around-comment: [ 2, { beforeBlockComment: true, beforeLineComment: true, allowBlockStart: true } ]
  linebreak-style: [ 2, unix ]
  new-parens: 2
  newline-after-var: 2
  no-array-constructor: 2
  no-inline-comments: 2
  no-lonely-if: 2
  no-multiple-empty-lines: [ 2, { max: 1 } ]
  no-unneeded-ternary: 2
  one-var: [ 2, always ]
  operator-assignment: [ 2, always ]
  operator-linebreak: 2
  quote-props: [ 2, as-needed, { keywords: true } ]
  space-before-function-paren: [ 2, { anonymous: always, named: never } ]
  space-in-parens: [ 2, never ]
  space-infix-ops: [ 2, { int32Hint: true } ]
  space-unary-ops: [ 2, { words: true, nonwords: false } ]
  arrow-parens: [ 2, as-needed ]
  arrow-spacing: 2
  constructor-super: 2
  no-class-assign: 2
  no-const-assign: 2
  no-this-before-super: 2
  prefer-spread: 2
  prefer-template: 2
  require-yield: 2
  func-names: 0
  max-depth: [ 2, 4 ]
  max-len: [ 2, 120, 2 ]
  max-params: [ 2, 10 ]
  no-console: 0
  id-length: 0
  no-negated-condition: 2
  no-mixed-spaces-and-tabs: [ 2, false ]
