---
linters:
  QualifyingElement:
    enabled: false
  StringQuotes:
    style: double_quotes
  IdSelector:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  SelectorDepth:
    enabled: false
  NestingDepth:
    enabled: false